### ISSUE TITLE
Move handler.rb to command_handlers folder

### ISSUE THREAD

**Issue by antonpaisov** [mpraglowski/cqrs-es-sample-with-res#10]
I would like to move https://github.com/mpraglowski/cqrs-es-sample-with-res/blob/master/lib/command/handler.rb to `command_handlers` folder, due to the fact that those are handlers, inheriting from this class, not commands.

What do you think? I think it'll be more clear that way.

**Comment by antonpaisov** [comment]
no longer relevant

**Comment by thewoolleyman** [comment]
@antonpaisov   Why do you say this is no longer relevant?  It seems like it would make more sense as a `CommandHandlers::Base` class in the `command_handlers` folder.  It confused me the first time I looked at it, because I thought it had something to do with the `Command` namespace, which it doesn't.

Thanks,
-- Chad

**Comment by antonpaisov** [comment]
hey @thewoolleyman!
Here's a PR regarding this issue #11. Discussion about it is there ;)

**Comment by antonpaisov** [comment]
but I still think that it would make more sense under the `CommandHandlers::Base`, because it really doesn't have anything to do with `Command`.
